name: Deploy docs

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configure Git
        run: |
          git config --global user.name "Savinnsk"
          git config --global user.email "saviodocuments@gmail.com"

      - name: Set Git Remote URL
        run: |
          git remote set-url origin git@github.com:savinnsk/DSystem.git

      - run: npm i

      - run: npm run build

      - name: Deploy storybook
        working-directory: ./packages/docs
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd storybook-static
          git init
          git config user.name "GH Pages Bot"
          git config user.email "hello@ghbot.com"
          git config commit.gpgsign false
          git checkout -b gh-pages
          touch .nojekyll
          git add .
          git commit -m "Deploy Storybook to GitHub Pages"
          git push --force --quiet https://github.com/savinnsk/DSystem.git gh-pages
